# Generated by Django 5.1.7 on 2025-04-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_orderlineitem_delete_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_services',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='order',
            name='service_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='additional_services',
            field=models.JSONField(default=list),
        ),
    ]
