# Generated by Django 5.1.7 on 2025-04-21 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_cartitem_services'),
        ('checkout', '0005_rename_full_name_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('standard production', 'Standard Production'), ('priority delivery', 'Priority Delivery'), ('48h express delivery', '48h Express Delivery'), ('24h express delivery', '24h Express Delivery')], default='standard', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='orders_items', to='cart.cartitem'),
        ),
        migrations.AddField(
            model_name='order',
            name='save_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='checkout.order'),
        ),
    ]
