# Generated by Django 5.1.7 on 2025-04-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_order_delivery_option_order_items_order_save_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='print_data_file',
            field=models.FileField(blank=True, null=True, upload_to='print_uploads/'),
        ),
    ]
