# Generated by Django 5.1.7 on 2025-05-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_order_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='print_data_file',
        ),
        migrations.DeleteModel(
            name='PrintData',
        ),
    ]
