# Generated by Django 5.1.7 on 2025-05-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_remove_order_print_data_file_delete_printdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_option',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='delivery_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
        ),
    ]
