# Generated by Django 5.1.7 on 2025-05-08 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_order_street_address2_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='street_address2',
        ),
    ]
