# Generated by Django 5.1.7 on 2025-05-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_remove_order_street_address2'),
    ]

    operations = [

    ]
