# Generated by Django 5.1.7 on 2025-04-22 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='user_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service_type', models.CharField(choices=[('Own Print Data Upload', 'Own Print Data Upload'), ('Online Designer', 'Online Designer'), ('Design Service', 'Design Service')], max_length=100)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='print_data_files',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='homepage.printdata'),
        ),
    ]
