# Generated by Django 5.1.7 on 2025-04-23 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_printdata_profile_print_data_files'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printdata',
            options={'verbose_name': 'Print Data', 'verbose_name_plural': 'Print Data Entries'},
        ),
    ]
