# Generated by Django 5.1.7 on 2025-05-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='send_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent')], default='Pending', max_length=10),
        ),
    ]
