# Generated by Django 5.1.7 on 2025-05-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_newsletter_send_at_newsletter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='purchased_products',
            field=models.ManyToManyField(blank=True, related_name='purchased_products', to='homepage.product'),
        ),
    ]
