# Generated by Django 5.1.7 on 2025-05-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='print_data_files',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.DeleteModel(
            name='PrintData',
        ),
    ]
