# Generated by Django 5.1.7 on 2025-05-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_order_complete_order_date_completed_and_more'),
        ('homepage', '0011_remove_profile_print_data_files_profile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='checkout.order'),
        ),
    ]
