# Generated by Django 5.1.7 on 2025-05-08 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_profile_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='street_address2',
        ),
    ]
