# Generated by Django 5.1.7 on 2025-05-09 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_contactrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactRequest',
        ),
    ]
