# Generated by Django 5.1.7 on 2025-04-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cartitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
