# Generated by Django 5.1.7 on 2025-04-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='services',
            field=models.JSONField(default=list),
        ),
    ]
