# Generated by Django 5.1.7 on 2025-04-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_cartitem_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='services',
            field=models.TextField(),
        ),
    ]
