# Generated by Django 5.1.7 on 2025-04-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_cartitem_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='services',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='is_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
