# Generated by Django 5.1.7 on 2025-04-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_remove_cartitem_services_cartitem_is_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='services',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
