# Generated by Django 5.1.7 on 2025-05-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_cartitem_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_option',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
