# Generated by Django 5.1.7 on 2025-03-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fallback_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
