# Generated by Django 5.1.7 on 2025-04-04 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_sizes_productsize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsize',
            old_name='quantity_available',
            new_name='customer_order_quantity',
        ),
        migrations.CreateModel(
            name='QuantityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_options', to='products.product')),
            ],
        ),
    ]
