# Generated by Django 5.1.7 on 2025-04-04 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_quantity_available_productsize_customer_order_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantityoption',
            old_name='product',
            new_name='product_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='quantityoption',
            name='size',
        ),
    ]
