# Generated by Django 5.1.7 on 2025-04-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_product_quantityoption_product_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantityoption',
            old_name='product_size',
            new_name='product',
        ),
    ]
