# Generated by Django 5.1.7 on 2025-04-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_product_size_quantityoption_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='customer_order_quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='additional_services',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='quantities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
