# Generated by Django 5.1.7 on 2025-04-10 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_additional_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sizes_set', to='products.product'),
        ),
        migrations.AlterField(
            model_name='quantityoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_options_set', to='products.product'),
        ),
    ]
